#!/bin/sh

# Set LunarVim to open typing "vim"
alias vim='zsh ~/.local/bin/lvim'

# Easy access to config files
alias vimrc="vim $XDG_CONFIG_HOME/lvim/config.lua"
alias zshrc="vim $XDG_CONFIG_HOME/zsh/.zshrc"
alias zsh_aliases="vim $XDG_CONFIG_HOME/zsh/zsh-aliases"
alias zsh_exports="vim $XDG_CONFIG_HOME/zsh/zsh-exports"

# Git related
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gl='git log --oneline'
alias gb='git checkout -b'
alias gd='git diff'

alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# Use this in case at some point in your life you need to work regularly with 
# different OS. This way you'll abstract the behavior from the command itself.
case "$(uname -s)" in
Darwin)
	# echo 'Mac OS X'
	alias ls='ls -G'
	;;

Linux)
	# Create directories faster
    alias mkdir='mkdir -p -v'

    # confirm before overwriting something
    alias cp="cp -i"
    alias mv='mv -i'
    alias rm='rm -i'

    # Change directory backward
    alias ..='cd ..;pwd'
    alias ...='cd ../..;pwd'
    alias ....='cd ../../..;pwd'

    # Colorize output (good for log files)
	  alias ls='ls --color=auto'
	  alias ll='ls -lX --color=auto'
	  alias la='ls -laX --color=auto'
    alias grep='grep --color=auto'
    alias egrep='egrep --color=auto'
    alias fgrep='fgrep --color=auto'

    # Other aliases
    alias h='history'
    # alias open='xdg-open'
    alias tree='tree --dirsfirst -F -C'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac
