#!/bin/sh

export PATH="$HOME/.local/bin":$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.fnm:$PATH

export MANPAGER='nvim +Man!'
export MANWIDTH=999
export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm


# For QT Themes
export QT_QPA_PLATFORMTHEME=qt5ct

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/alemoreno991/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/alemoreno991/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/alemoreno991/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/alemoreno991/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Environment variables set everywhere
export EDITOR="lvim"
export TERMINAL="alacritty"
export BROWSER="google-chrome"
