#!/bin/sh

export PATH="$HOME/.local/bin":$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.fnm:$PATH

export MANPAGER='nvim +Man!'
export MANWIDTH=999
export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm


# For QT Themes
export QT_QPA_PLATFORMTHEME=qt5ct

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/alemoreno991/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/alemoreno991/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/alemoreno991/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/alemoreno991/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Environment variables set everywhere
export EDITOR="lvim"
export TERMINAL="alacritty"
export BROWSER="google-chrome"

# export CC=/usr/bin/clang
# export CXX=/usr/bin/clang++

# ROS related (something to do with URDF)
export LC_NUMERIC="en_US.UTF-8"

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/.mujoco/mujoco-2.2.1/bin/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia/
export PATH="$LD_LIBRARY_PATH:$PATH"
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/

export GNUPLOT_DRIVER_DIR=/home/alemoreno991/mambaforge/envs/ros_noetic/libexec/gnuplot/5.4
